### ISSUE TITLE
Fingerprint is not suggested on Chrome / Android

### ISSUE THREAD

**Issue by bpolaszek** [web-auth/symfony-demo#125]
Hello there, and thank you for the awesome demo! :-)

Just 1 question: the demo works well with my Macbook's built-in fingerprint device, but not with my Google Pixel 3a's one (Chrome browser). The fingerprint is just not suggested in the options. I thought at first Chrome/Android was not compatible yet, but fingerprint is correctly suggested on some other implementations, Github 2FA for example (same device/browser):

| webauthn.spomky-labs.com | Github.com |
| ----------------------------- | ----------- |
| ![Screenshot_20200310-141042](https://user-images.githubusercontent.com/5569077/76316172-68de1980-62da-11ea-93cf-9555e696bb81.png) | ![Screenshot_20200310-141105](https://user-images.githubusercontent.com/5569077/76316185-70052780-62da-11ea-86b2-a98d7d54d01c.png) |

Any ideas?

Thank you,
Ben

**Comment by Spomky** [comment]
Hi @bpolaszek,

The fingerprint is suggested on my Android device and on the demo.
Is your device rooted or not manufactured by a non-certified manufacturer? That could be the reason for this missing option.

My understanding of the [Android documentation](https://developer.android.com/training/safetynet/attestation) is that it only work with certified devices (`ctsProfileMatch` shall be `true`).
Hereafter the requirements. As you will see, it is very restrictive!

Device Status | Value of ctsProfileMatch
-- | --
Certified, genuine device that passes CTS | true
Certified device with unlocked bootloader | false
Genuine but uncertified device, such as when the manufacturer doesn't     apply for certification | false
Device with custom ROM (not rooted) | false
Emulator | false
No device (such as a protocol emulating script) | false
Signs of system integrity compromise, one of which may be rooting | false
Signs of other active attacks, such as API hooking | false

It works fine on my device so this is not coming from the protocol or the server, but the device.

![Screenshot_20200310-143400](https://user-images.githubusercontent.com/1091072/76319031-e3a93380-62de-11ea-9f45-57b50098055e.png)

**Comment by bpolaszek** [comment]
Oh, OK I get it, but it's a different use case.
I have a non-rooted Pixel 3a with up-to-date Android stock.

I originally **signed up** with the user _ben_ from _Macbook / Chrome / fingerprint_.
Then, I can **sign in** with the user  _ben_ from _Macbook / Chrome / fingerprint_.
But when I try to **sign in** with the user  _ben_  from _Pixel 3a / Android / Chrome_, _fingerprint_ is not suggested (even though it wouldn't work).

Then, I **signed up** with a new user _ben_android_ from  _Pixel 3a / Android / Chrome_, and _fingerprint_ was suggested (along with the other options).
When I try to **sign in** with the user _ben_android_ from  _Pixel 3a / Android / Chrome_, **only** fingerprint is suggested (and it works).
When I try to **sign in** with the user _ben_android_ from _Macbook / Chrome_, USB device and fingerprint are suggested, but clicking on fingerprint immediately throws and error (without prompting to press the fingerprint device).

| Macbook -> _ben_android_ | Click on _fingerprint_ |
| ----- | ------- |
| <img width="439" alt="Capture d’écran 2020-03-10 à 15 29 22" src="https://user-images.githubusercontent.com/5569077/76322889-3a653c00-62e4-11ea-8445-0f581a815ac9.png"> | <img width="438" alt="Capture d’écran 2020-03-10 à 15 29 30" src="https://user-images.githubusercontent.com/5569077/76322921-4650fe00-62e4-11ea-8874-9d7ee70d242b.png"> |

So, it looks like the problem occurs when using multiple devices. Out of the scope of the demo, will figure out how to handle this myself. Just FYI.

Thank you for your work!
Ben

**Comment by Spomky** [comment]
Oh OK I get it too!

Indeed the support for multiples authenticator is not implemented in this demo that's why you cannot use both the laptop and the smartphone for the same user account.

This feature is still possible and it's even recommended to register multiple authenticators.
Few days ago, I created another demo, much more simpler. You will find it here: https://github.com/web-auth/demo-symfony

This other demo supports multiple authenticator registration so you should be able to add your laptop, an USB key, your smartphone or whatever device you want (no limitation).
This repository has just 2 commits: after the installation of Symfony5 and after the installation of the bundle and all the stuf.

Anyway I will take time to enable the multiple authentication feature support for this demo, I will re-open the issue to keep it in my mind.

**Comment by Spomky** [comment]
Multiple authenticator is now available in the last demo version

**Comment by bpolaszek** [comment]
Thank you @Spomky! 🙏
