### ISSUE TITLE
bug page https://webauthn.spomky-labs.com/register ?

### ISSUE THREAD

**Issue by stloc** [web-auth/symfony-demo#163]
Bonjour, 
à la suite de votre vidéo https://www.youtube.com/watch?v=Y2_0omg1CFk, je souhaite tester la démo mais je suis bloqué sur la page https://webauthn.spomky-labs.com/register

![image](https://user-images.githubusercontent.com/4832070/223419925-dc577ce2-ac8c-4e5d-a2b0-a0a54f4f1757.png)

**Comment by Spomky** [comment]
Aïe! Oui effectivement la démo ne fonctionne plus. Merci de me l'avoir signalé.
Je vais investiguer et corriger.
En attendant, d'autres démo existent dont celle-ci que je trouve très bien : https://webauthn.io/

**Comment by stloc** [comment]
super cette démo https://webauthn.io/ aussi, merci. Ils ne proposent pas PHP ?

**Comment by Spomky** [comment]
J'avais ouvert une PR pour ajouter des références, mais elle n'a pas évolué depuis.
Je viens de mettre à jour la démo et ça fonctionne de nouveau.

**Comment by stloc** [comment]
parfait, Merci !
