### ISSUE TITLE
Rename repo to something besides symfony-demo

### ISSUE THREAD

**Issue by tacman** [web-auth/symfony-demo#253]
### Description

Thanks for releasing this -- great to see a demo using some of newest Symfony tools.

What do you think of renaming this repo to symfony-webauth-demo, to be clear that it's not simply the demo that's created with the symfony new --demo command?  That will also make it easier to maintain forks of the repo, and distinguish it from the 1700 forks of https://github.com/symfony/demo

**Comment by Spomky** [comment]
> What do you think of renaming this repo to symfony-webauth-demo

Hi,
Yes indeed, this repo could be renamed. web-auth/symfony-webauthn-demo looks good to me.

**Comment by Spomky** [comment]
Done.
No links to be changed here and GitHub redirects the old repo name to the correct one.
Thank you for the proposal and happy coding.
